### ISSUE TITLE
NodeJS: Cannot read property 'blk_out' of undefined

### ISSUE THREAD

**Issue by zepedrorocha** [moinejf/abc2svg#11]
Hello. When I try to run in a command line I got the following error:

Using the following setup 
Win10, node v7.4.0, npm v.5.3.0

package.json
...
"scripts": {
 "start": "abc2svg z.xml z.abc"
}
..

> npm start
> abc2svg z,xml z.abc

....\abc2svg\toxhtml.js:34
        abc.blk_out();                                                                                      ^

TypeError: Cannot read property 'blk_out' of undefined
    at abort (.....\toxhtml.js:34:5)
    at do_file (....\node_modules\abc2svg\cmdline.js:62:3)
    at abc_cmd (.....\node_modules\abc2svg\cmdline.js:97:3)
    at Object.<anonymous> (....\node_modules\abc2svg\abc2svg:81:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)                                                                at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

**Comment by moinejf** [comment]
Should be fixed by commit 504b763b7dd71f16a5e77a77f86ac388b7b14705
As there is no new release yet, you may apply yourself the patch to cmdline.js.

**Comment by zepedrorocha** [comment]
I did the fix manually and it works, but I will wait for the npm package to fully test it. TY.

**Comment by zepedrorocha** [comment]
Tested in the 1.14.0 version and it works. Thanks
