### ISSUE TITLE
testcase fails: 3017_beat_compressor

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#56]
```
X:3017
F:3017_beat_compressor
T:beat_compressor
C:
S:
M:8/4
L:1/4
Q:1/4=120
K:C
I:linewarn 0
%%score 1 2
V:1 clef=treble name="Sopran" snm="S" octave=-1
[P:monotoneous up] 
cdefgabc' |
[P:monotoneous down] 
c'bagfedc |
[P: invert] 
cdefgfed |
[P: same note] 
cddeffec |
[P: unison collision]
[cd][de][ef]g[b]c'd'[fe'] |
[P: vertical]
cdcdcdcd
%
[P:cross voice monotoneous up] 
cdefgabc' |
[P:monotoneous down] 
c'bagfedc |
[P: invert] 
cdefgfed |
[P: same note] 
cddeffec |
[P: unison collision]
[cd][de][ef]g[b]c'd'[ee'] | % todo: collision with "c"%
V:2 octave=-2
c4 d4 |
c4 d4 |
c4 d4 |
c4 d4 |
c4 d4 |c4 d4 |
```

on abc2svg-1.15.0-32-g 29e7747 results in 

```
Cannot read property 'ts_next' of undefined
*** Abort ***
TypeError: Cannot read property 'ts_next' of undefined
    at cut_tune (/private/tmp/toto.js:9311:18)
    at output_music (/private/tmp/toto.js:12040:3)
    at generate (/private/tmp/toto.js:18181:2)
    at end_tune (/private/tmp/toto.js:7139:3)
    at Abc.tosvg (/private/tmp/toto.js:7193:5)
    at do_file (/private/tmp/toto.js:20422:7)
    at abc_cmd (/private/tmp/toto.js:20452:3)
    at Object. (/private/tmp/toto.js:20656:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by bwl21** [comment]
verified with  abc2svg: | 1.15.0-43-g cb84529

No longer crashes. Thanks
