### ISSUE TITLE
testcase fail: 1_segne-du-maria

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#57]
```
% - settings to improve Handling in Zupfnoter
I:measurenb 1
I:linewarn 0
I:staffnonote 2
% --------------
X:1
F:1_segne-du-maria
T:Segne du, Maria
C:
S:
M:4/4
L:1/4
Q:1/4=100
I:transpose +2
K:C
%
%
%%score 1 2
%
V:1 clef=treble name=
G> F E G|c2 A2|G> A G D |E3 z| G> F E G | c2 B2 |A E ^F> F| G3 z|D>DE F |G2E2|F> G A F|D3z|E G c B|A>G F2|E G E>D|G3 z|A>Adc|B>AG2|D F E>D|C4|]
V:2 clef=treble
C3B,|A,2F,2|B,2G,B,|C3z|G,B,CB,|A,2G,2|C2D2|G,3z|G,B,_B,A,|B,2C>_B,|A,G,A,C|G,3z|CB,A,B,|C^CD2|A,B,G,2|C3z|FGF^F|GDG,2|F,2G,2|C3|]
```

Yields

```
Cannot read property '0' of undefined
*** Abort ***
TypeError: Cannot read property '0' of undefined
    at set_kv_parm (/private/tmp/toto.js:5:155650)
    at get_voice (/private/tmp/toto.js:5:241092)
    at do_info (/private/tmp/toto.js:5:162885)
    at Abc.tosvg (/private/tmp/toto.js:5:98880)
    at do_file (/private/tmp/toto.js:79:7)
    at abc_cmd (/private/tmp/toto.js:109:3)
    at Object.<anonymous> (/private/tmp/toto.js:312:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by bwl21** [comment]
verified with  1.15.0-43-g cb84529

It no longer crashes but reports the missing value for name=

Thanks
