### ISSUE TITLE
Another problem of abc2svg - in context with line ending, %%text and unfilled voices

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#73]
Yes the following example has errors, but it causes abc2svg to fail

```
Cannot read property 'v' of undefined
abc2svg tosvg bug - stack:
TypeError: Cannot read property 'v' of undefined
    at init_music_line (http://moinejf.free.fr/js/abc2svg-1.js:5:131839)
    at set_piece (http://moinejf.free.fr/js/abc2svg-1.js:5:147939)
    at output_music (http://moinejf.free.fr/js/abc2svg-1.js:5:151262)
    at generate (http://moinejf.free.fr/js/abc2svg-1.js:5:231634)
    at end_tune (http://moinejf.free.fr/js/abc2svg-1.js:5:94497)
    at Abc.tosvg (http://moinejf.free.fr/js/abc2svg-1.js:5:99410)
    at render (http://moinejf.free.fr/js/edit-1.js:1:3243)
```

Sorry, I could not boil it down further. The fail goes away when I

* remove the text at the end
* replace `c/ccc`by `cccc`
* remove the declaration of V:3 V:4

```
X:1
T:Menuettcc
F:397_Menuet
Z:
%%scale 1
%%pagewidth 20cm
%%score  1 2
L:1/4
M:none
K:G shift=EB,
V:1 treble nm="32I" snm="32I"
L:1/8
V:2 treble 
V:3 bass
V:4 bass
V:1
 [K:G][M:3/4][K:treble]!mf! d2 c/ccc | c6 | c6 | c6 |c6 | %6
 c6 | c6 | c6 |c6 | c6 | c6 | c6|c6 | %14
 c6| c6 |c6 ::c6 | c6 | c6|c6 | c6 | c6 | %23
c6 | d6 |c6| e2 (GF G2) | c6 | c6 |c6 |c6 | %31
 c6| c6 |] %33
V:2
 [M:3/4][K:bass] C3 | B,3 | C3 | C3 | C3 |C3 | C3 | C3 | %9
 C3 |C3 | C3 | C3| C3 | C3 | C3 |C3 ::C3| C3| %19
 C3| C3 | C3 | C3 | C3 | C3 | C3 | C3 |C3 | C3 | %29
 C3| C3 | C3 |C3 |] %33
%
%% text note
```

**Comment by moinejf** [comment]
Should be fixed. Thanks.

**Comment by bwl21** [comment]
I verified this in 1.15.18. It does not crash anymore. Just for the records. The text note is placed after the end of V:1. This is not a problem at all, but interesting to know. No attempt should be made to change it, since it is a weird situation either.

Thanks for the fix. -> Close

**Comment by moinejf** [comment]
The %%text.. are always put in the main voice (first declared voice or first in %%score).
