### ISSUE TITLE
crash with I:combinevoices 1

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#91]
## Problem

```
X:1
I:combinevoices 1
K:C
V:1
C
```

Produces

```
Cannot read property 'replace' of undefined
abc2svg tosvg bug - stack:
TypeError: Cannot read property 'replace' of undefined
    at error (http://localhost:63342/abc2svg/abc2svg-1.js:167:13)
    at syntax (http://localhost:63342/abc2svg/abc2svg-1.js:209:2)
    at set_format (http://localhost:63342/abc2svg/abc2svg-1.js:6942:3)
    at do_pscom (http://localhost:63342/abc2svg/abc2svg-1.js:18031:2)
    at Abc.tosvg (http://localhost:63342/abc2svg/abc2svg-1.js:7540:4)
    at render2 (http://localhost:63342/abc2svg/edit-1.js:1:3353)
    at render (http://localhost:63342/abc2svg/edit-1.js:1:3071)
```
## Reason

format.js line 598 parameters for syntax() are wrong

**Comment by bwl21** [comment]
tested with 0ea68e5
