### ISSUE TITLE
crash with I:ambitus and changing clefs

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#92]
```
X:121
T:xxx
I:ambitus=1
K:C
V:3 clef=bass name="Tenor" snm="T"
V:3 name="Tenor" snm="T"
D[V:3 treble]GF ED C2 CC |
B,2 B,2 C2 CC | D6 :|]
```

results in 

```
Cannot read property 'pit' of undefined
abc2svg tosvg bug - stack:
TypeError: Cannot read property 'pit' of undefined
    at draw_symbols (eval at js_inject (http://localhost:63342/abc2svg/abc2svg-1.js:215:3), <anonymous>:15:10)
    at draw_all_sym (http://localhost:63342/abc2svg/abc2svg-1.js:5979:4)
    at Object.output_music [as om] (http://localhost:63342/abc2svg/abc2svg-1.js:12201:4)
    at output_music (eval at js_inject (http://localhost:63342/abc2svg/abc2svg-1.js:215:3), <anonymous>:32:10)
    at generate (http://localhost:63342/abc2svg/abc2svg-1.js:18124:3)
    at end_tune (http://localhost:63342/abc2svg/abc2svg-1.js:7315:3)
    at Abc.tosvg (http://localhost:63342/abc2svg/abc2svg-1.js:7697:3)
    at render2 (http://localhost:63342/abc2svg/edit-1.js:1:3353)
    at render (http://localhost:63342/abc2svg/edit-1.js:1:3071)
```

**Comment by bwl21** [comment]
Tested with 0ea68e5
